export const SA_VEHICLES = [
  { id: 400, model: 'landstal', name: 'Landstalker' },
  { id: 401, model: 'bravura', name: 'Bravura' },
  { id: 402, model: 'buffalo', name: 'Buffalo' },
  { id: 403, model: 'linerun', name: 'Linerunner' },
  { id: 404, model: 'peren', name: 'Pereniel' },
  { id: 405, model: 'sentinel', name: 'Sentinel' },
  { id: 406, model: 'dumper', name: 'Dumper' },
  { id: 407, model: 'firetruk', name: 'Firetruck' },
  { id: 408, model: 'trash', name: 'Trashmaster' },
  { id: 409, model: 'stretch', name: 'Stretch' },
  { id: 410, model: 'manana', name: 'Manana' },
  { id: 411, model: 'infernus', name: 'Infernus' },
  { id: 412, model: 'voodoo', name: 'Voodoo' },
  { id: 413, model: 'pony', name: 'Pony' },
  { id: 414, model: 'mule', name: 'Mule' },
  { id: 415, model: 'cheetah', name: 'Cheetah' },
  { id: 416, model: 'ambulan', name: 'Ambulance' },
  { id: 417, model: 'leviathn', name: 'Leviathan' },
  { id: 418, model: 'moonbeam', name: 'Moonbeam' },
  { id: 419, model: 'esperant', name: 'Esperanto' },
  { id: 420, model: 'taxi', name: 'Taxi' },
  { id: 421, model: 'washing', name: 'Washington' },
  { id: 422, model: 'bobcat', name: 'Bobcat' },
  { id: 423, model: 'mrwhoop', name: 'Mr Whoopee' },
  { id: 424, model: 'bfinject', name: 'BF Injection' },
  { id: 425, model: 'hunter', name: 'Hunter' },
  { id: 426, model: 'premier', name: 'Premier' },
  { id: 427, model: 'enforcer', name: 'Enforcer' },
  { id: 428, model: 'securica', name: 'Securicar' },
  { id: 429, model: 'banshee', name: 'Banshee' },
  { id: 430, model: 'predator', name: 'Predator' },
  { id: 431, model: 'bus', name: 'Bus' },
  { id: 432, model: 'rhino', name: 'Rhino' },
  { id: 433, model: 'barracks', name: 'Barracks' },
  { id: 434, model: 'hotknife', name: 'Hotknife' },
  { id: 435, model: 'artict1', name: 'Article Trailer' },
  { id: 436, model: 'previon', name: 'Previon' },
  { id: 437, model: 'coach', name: 'Coach' },
  { id: 438, model: 'cabbie', name: 'Cabbie' },
  { id: 439, model: 'stallion', name: 'Stallion' },
  { id: 440, model: 'rumpo', name: 'Rumpo' },
  { id: 441, model: 'rcbandit', name: 'RC Bandit' },
  { id: 442, model: 'romero', name: 'Romero' },
  { id: 443, model: 'packer', name: 'Packer' },
  { id: 444, model: 'monster', name: 'Monster' },
  { id: 445, model: 'admiral', name: 'Admiral' },
  { id: 446, model: 'squalo', name: 'Squalo' },
  { id: 447, model: 'seaspar', name: 'Seasparrow' },
  { id: 448, model: 'pizzaboy', name: 'Pizzaboy' },
  { id: 449, model: 'tram', name: 'Tram' },
  { id: 450, model: 'artict2', name: 'Article Trailer 2' },
  { id: 451, model: 'turismo', name: 'Turismo' },
  { id: 452, model: 'speeder', name: 'Speeder' },
  { id: 453, model: 'reefer', name: 'Reefer' },
  { id: 454, model: 'tropic', name: 'Tropic' },
  { id: 455, model: 'flatbed', name: 'Flatbed' },
  { id: 456, model: 'yankee', name: 'Yankee' },
  { id: 457, model: 'caddy', name: 'Caddy' },
  { id: 458, model: 'solair', name: 'Solair' },
  { id: 459, model: 'topfun', name: 'Topfun Van' },
  { id: 460, model: 'skimmer', name: 'Skimmer' },
  { id: 461, model: 'pcj600', name: 'PCJ-600' },
  { id: 462, model: 'faggio', name: 'Faggio' },
  { id: 463, model: 'freeway', name: 'Freeway' },
  { id: 464, model: 'rcbaron', name: 'RC Baron' },
  { id: 465, model: 'rcraider', name: 'RC Raider' },
  { id: 466, model: 'glendale', name: 'Glendale' },
  { id: 467, model: 'oceanic', name: 'Oceanic' },
  { id: 468, model: 'sanchez', name: 'Sanchez' },
  { id: 469, model: 'sparrow', name: 'Sparrow' },
  { id: 470, model: 'patriot', name: 'Patriot' },
  { id: 471, model: 'quad', name: 'Quad' },
  { id: 472, model: 'coastg', name: 'Coastguard' },
  { id: 473, model: 'dinghy', name: 'Dinghy' },
  { id: 474, model: 'hermes', name: 'Hermes' },
  { id: 475, model: 'sabre', name: 'Sabre' },
  { id: 476, model: 'rustler', name: 'Rustler' },
  { id: 477, model: 'zr350', name: 'ZR-350' },
  { id: 478, model: 'walton', name: 'Walton' },
  { id: 479, model: 'regina', name: 'Regina' },
  { id: 480, model: 'comet', name: 'Comet' },
  { id: 481, model: 'bmx', name: 'BMX' },
  { id: 482, model: 'burrito', name: 'Burrito' },
  { id: 483, model: 'camper', name: 'Camper' },
  { id: 484, model: 'marquis', name: 'Marquis' },
  { id: 485, model: 'baggage', name: 'Baggage' },
  { id: 486, model: 'dozer', name: 'Dozer' },
  { id: 487, model: 'maverick', name: 'Maverick' },
  { id: 488, model: 'newsvan', name: 'News Maverick' },
  { id: 489, model: 'rancher', name: 'Rancher' },
  { id: 490, model: 'fbiranch', name: 'FBI Rancher' },
  { id: 491, model: 'virgo', name: 'Virgo' },
  { id: 492, model: 'greenwoo', name: 'Greenwood' },
  { id: 493, model: 'jetmax', name: 'Jetmax' },
  { id: 494, model: 'hotring', name: 'Hotring Racer' },
  { id: 495, model: 'sandking', name: 'Sandking' },
  { id: 496, model: 'blistac', name: 'Blista Compact' },
  { id: 497, model: 'polmav', name: 'Police Maverick' },
  { id: 498, model: 'boxville', name: 'Boxville' },
  { id: 499, model: 'benson', name: 'Benson' },
  { id: 500, model: 'mesa', name: 'Mesa' },
  { id: 501, model: 'rcgoblin', name: 'RC Goblin' },
  { id: 502, model: 'hotrina', name: 'Hotring Racer 2' },
  { id: 503, model: 'hotrinb', name: 'Hotring Racer 3' },
  { id: 504, model: 'bloodra', name: 'Bloodring Banger' },
  { id: 505, model: 'rnchlure', name: 'Rancher 2' },
  { id: 506, model: 'supergt', name: 'Super GT' },
  { id: 507, model: 'elegant', name: 'Elegant' },
  { id: 508, model: 'journey', name: 'Journey' },
  { id: 509, model: 'bike', name: 'Bike' },
  { id: 510, model: 'mtbike', name: 'Mountain Bike' },
  { id: 511, model: 'beagle', name: 'Beagle' },
  { id: 512, model: 'cropdust', name: 'Cropduster' },
  { id: 513, model: 'stunt', name: 'Stuntplane' },
  { id: 514, model: 'petro', name: 'Tanker' },
  { id: 515, model: 'rdtrain', name: 'Roadtrain' },
  { id: 516, model: 'nebula', name: 'Nebula' },
  { id: 517, model: 'majestic', name: 'Majestic' },
  { id: 518, model: 'buccanee', name: 'Buccaneer' },
  { id: 519, model: 'shamal', name: 'Shamal' },
  { id: 520, model: 'hydra', name: 'Hydra' },
  { id: 521, model: 'fcr900', name: 'FCR-900' },
  { id: 522, model: 'nrg500', name: 'NRG-500' },
  { id: 523, model: 'copbike', name: 'HPV1000' },
  { id: 524, model: 'cement', name: 'Cement Truck' },
  { id: 525, model: 'towtruck', name: 'Towtruck' },
  { id: 526, model: 'fortune', name: 'Fortune' },
  { id: 527, model: 'cadrona', name: 'Cadrona' },
  { id: 528, model: 'fbitruck', name: 'FBI Truck' },
  { id: 529, model: 'willard', name: 'Willard' },
  { id: 530, model: 'forklift', name: 'Forklift' },
  { id: 531, model: 'tractor', name: 'Tractor' },
  { id: 532, model: 'combine', name: 'Combine' },
  { id: 533, model: 'feltzer', name: 'Feltzer' },
  { id: 534, model: 'remingtn', name: 'Remington' },
  { id: 535, model: 'slamvan', name: 'Slamvan' },
  { id: 536, model: 'blade', name: 'Blade' },
  { id: 537, model: 'freight', name: 'Freight' },
  { id: 538, model: 'streak', name: 'Streak' },
  { id: 539, model: 'vortex', name: 'Vortex' },
  { id: 540, model: 'vincent', name: 'Vincent' },
  { id: 541, model: 'bullet', name: 'Bullet' },
  { id: 542, model: 'clover', name: 'Clover' },
  { id: 543, model: 'sadler', name: 'Sadler' },
  { id: 544, model: 'firela', name: 'Firetruck LA' },
  { id: 545, model: 'hustler', name: 'Hustler' },
  { id: 546, model: 'intruder', name: 'Intruder' },
  { id: 547, model: 'primo', name: 'Primo' },
  { id: 548, model: 'cargobob', name: 'Cargobob' },
  { id: 549, model: 'tampa', name: 'Tampa' },
  { id: 550, model: 'sunrise', name: 'Sunrise' },
  { id: 551, model: 'merit', name: 'Merit' },
  { id: 552, model: 'utility', name: 'Utility Van' },
  { id: 553, model: 'nevada', name: 'Nevada' },
  { id: 554, model: 'yosemite', name: 'Yosemite' },
  { id: 555, model: 'windsor', name: 'Windsor' },
  { id: 556, model: 'monstera', name: 'Monster 2' },
  { id: 557, model: 'monsterb', name: 'Monster 3' },
  { id: 558, model: 'uranus', name: 'Uranus' },
  { id: 559, model: 'jester', name: 'Jester' },
  { id: 560, model: 'sultan', name: 'Sultan' },
  { id: 561, model: 'stratum', name: 'Stratum' },
  { id: 562, model: 'elegy', name: 'Elegy' },
  { id: 563, model: 'raindanc', name: 'Raindance' },
  { id: 564, model: 'rctiger', name: 'RC Tiger' },
  { id: 565, model: 'flash', name: 'Flash' },
  { id: 566, model: 'tahoma', name: 'Tahoma' },
  { id: 567, model: 'savanna', name: 'Savanna' },
  { id: 568, model: 'bandito', name: 'Bandito' },
  { id: 569, model: 'freibox', name: 'Freight Flat' },
  { id: 570, model: 'streakc', name: 'Streak Carriage' },
  { id: 571, model: 'kart', name: 'Kart' },
  { id: 572, model: 'mower', name: 'Mower' },
  { id: 573, model: 'duneride', name: 'Dune' },
  { id: 574, model: 'sweeper', name: 'Sweeper' },
  { id: 575, model: 'broadway', name: 'Broadway' },
  { id: 576, model: 'tornado', name: 'Tornado' },
  { id: 577, model: 'at400', name: 'AT-400' },
  { id: 578, model: 'dft30', name: 'DFT-30' },
  { id: 579, model: 'huntley', name: 'Huntley' },
  { id: 580, model: 'stafford', name: 'Stafford' },
  { id: 581, model: 'bf400', name: 'BF-400' },
  { id: 583, model: 'tug', name: 'Tug' },
  { id: 584, model: 'petrotr', name: 'Trailer 3' },
  { id: 585, model: 'emperor', name: 'Emperor' },
  { id: 586, model: 'wayfarer', name: 'Wayfarer' },
  { id: 587, model: 'euros', name: 'Euros' },
  { id: 588, model: 'hotdog', name: 'Hotdog' },
  { id: 589, model: 'club', name: 'Club' },
  { id: 591, model: 'tugstair', name: 'Tug Stairs' },
  { id: 592, model: 'androm', name: 'Andromada' },
  { id: 593, model: 'dodo', name: 'Dodo' },
  { id: 594, model: 'rccam', name: 'RC Cam' },
  { id: 595, model: 'launch', name: 'Launch' },
  { id: 596, model: 'copcarla', name: 'Police Car (LSPD)' },
  { id: 597, model: 'copcarsf', name: 'Police Car (SFPD)' },
  { id: 598, model: 'copcarru', name: 'Police Car (LVPD)' },
  { id: 600, model: 'picador', name: 'Picador' },
  { id: 601, model: 'swatvan', name: 'S.W.A.T.' },
  { id: 602, model: 'alpha', name: 'Alpha' },
  { id: 603, model: 'phoenix', name: 'Phoenix' },
  { id: 604, model: 'glenshit', name: 'Glendale Damaged' },
  { id: 605, model: 'sadlshit', name: 'Sadler Damaged' },
  { id: 606, model: 'bagboxa', name: 'Baggage Trailer A' },
  { id: 607, model: 'bagboxb', name: 'Baggage Trailer B' },
  { id: 609, model: 'boxburg', name: 'Boxville 2' },
  { id: 610, model: 'farmtr1', name: 'Farm Trailer' },
  { id: 611, model: 'utiltr1', name: 'Street Clean' },
]

export const SA_VEHICLE_MAP = Object.fromEntries(SA_VEHICLES.map(v => [v.id, v.name]))
